/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package puertoapp.app;

import javafx.application.Application;
import javafx.stage.Stage;
import puertoapp.app.tools.Vars;

public class App 
        extends Application {

    @Override
    public void start(Stage stage)
                    throws Exception {
        Vars.stage = stage;
        Vars.crearHandler("login");
        Vars.apph.launchWindow();
    }
    
}